package advent.solutions

import advent.*

class Day8Test
    extends ExampleValidator[8](
      14,
      -1,
    )(
      """............
        |........0...
        |.....0......
        |.......0....
        |....0.......
        |......A.....
        |............
        |............
        |........A...
        |.........A..
        |............
        |............""".stripMargin,
    )
